- name: Stop provisioned resources
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - vars/default.yml
  tasks:
    - ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": datagrid
      register: ec2_info
    - name: Terminate instances
      ec2:
        instance_ids: "{{item.instance_id}}"
        state: absent
        region: "{{ region }}"
      with_items: "{{ec2_info.instances}}"
    - name: Remove key
      ec2_key:
        name: infinispan
        region: "{{ region }}"
        state: absent