- name: Provision on EC2
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/all
  tasks:
    - name: Create data grid instances
      ec2:
        region: "{{ region }}"
        key_name: "{{ ssh_key }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: true
        exact_count: "{{ cluster_size }}"
        count_tag:
          Role: jdg
        instance_tags:
          Name: datagrid
          Role: jdg
      register: ec2
    - name: Create loader instances
      ec2:
        region: "{{ region }}"
        key_name: "{{ ssh_key }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: true
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: true
        exact_count: 1
        count_tag:
          Role: loader
        instance_tags:
          Name: datagrid
          Role: loader
      register: ec2
    - name: Wait for SSH to come up
      delegate_to: "{{ item.public_dns_name }}"
      wait_for_connection:
        delay: 60
        timeout: 320
      loop: "{{ ec2.instances }}"
    - name: Refresh inventory to ensure new instances exist in inventory
      meta: refresh_inventory

- name: install jdg nodes
  gather_facts: True
  hosts: jdg
  roles:
  - role: jdg
    vars:
      cloud: true

- name: install loader nodes
  gather_facts: True
  hosts: loader
  roles:
    - role: loader