---
- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash

- name: Install JVM
  shell: |
    source ~/.bashrc
    yes y | sdk install java 11.0.9.open-adpt

- name: Install jbang
  shell: |
    source ~/.bashrc
    yes y | sdk install jbang

- name: Create loader dir
  file:
    path: /opt/loader/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name:  Copy loader files
  copy:
    src: "{{ item }}"
    dest: /opt/loader
    mode: 755
  with_fileglob: "files/*"

- name: Loading data
  shell: |
    /opt/loader/loader.java --cache {{ cache_name }} --entries {{ entries }} --protocol {{ protocol }} --server {{ groups['jdg'][0] }} --phrase-size {{ phrase }} --write-batch {{ batch }}