########## Provisioning related variables

# Java version must be a string supported from SDKMan
java_version: 8.0.275.open-adpt

# The server zip, relative to the files/server folder
server_zip: jboss-datagrid-7.1.0-server.zip

# The server xml config to use. For custom config, copy it first to ```servers/overlay/standalone/configuration```. Defaults to "clustered.xml" or "cloud.xml"
# custom_server_config:

# The zip containing the appdynamics agent, relative to the files/agent folder
agent_zip: AppServerAgent-20.10.0.31173.zip

# Heap sizes
heap_size: -Xms20g -Xmx20g

# GC options for the server
gc_opts: -XX:+UseG1GC -XX:InitiatingHeapOccupancyPercent=0 -XX:MaxGCPauseMillis=200 -XX:GCPauseIntervalMillis=5000

# Agent options for the server
agent_opts: -Djboss.modules.system.pkgs=org.jboss.byteman,com.singularity -javaagent:/opt/agent/javaagent.jar

# Cluster size
cluster_size: 10

########## Initial data loading variables
# Cache name
cache_name: default

# Initial data loading
entries: 3000000

# Sample data phrase size
phrase: 100

# HotRod protocol
protocol: 2.5

# Load batch
batch: 1000

########## Stress test related variables
duration_min: 1

stress_threads: 10

write_percent: 70

########## AWS specific variables

# Region
region: eu-west-2

# Security group id
security_group: "sg-0a55ec7795af7a6a5"

# Instance type
instance_type: m4.2xlarge

# Image Id
image: "ami-08b993f76f42c3e2f"

# Subnet Id
subnet: "subnet-6f66d223"