---
- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash

- name: Install JVM
  shell: |
    source ~/.bashrc
    yes y | sdk install java {{ java_version }}

- name: Create server dir
  file:
    path: /opt/jdg/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Copy server
  copy:
    src: files/servers/{{ server_zip }}
    dest: ~/server.zip

- name: Extract Server
  unarchive:
    src: ~/server.zip
    dest: /opt/jdg
    remote_src: true

- name: obtain server dir
  shell: ls -d /opt/jdg/*server*/ | head -1
  register: server_dir

- name: Create the server symlink
  file:
    src: "{{ server_dir.stdout }}"
    dest: /opt/jdg/server
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  become: yes

- name: Overlay server files
  copy:
    src: ./files/servers/overlay/
    dest: /opt/jdg/server/
    directory_mode: 0775
  become: yes

- name: Add Heap sizes
  shell: sed -i "/^#PRESERV.*/a JAVA_OPTS=\"\$JAVA_OPTS {{ heap_size }}\""  /opt/jdg/*/bin/standalone.conf

- name: Add GC opts
  shell: sed -i "/^#PRESERV.*/a JAVA_OPTS=\"\$JAVA_OPTS {{ gc_opts }}\""  /opt/jdg/*/bin/standalone.conf

- stat:
    path: /opt/agent
  register: agent_dir

- name: Add Agent ops
  shell: sed -i "/^#PRESERV.*/a JAVA_OPTS=\"\$JAVA_OPTS {{ agent_opts }}\""  /opt/jdg/server/bin/standalone.conf
  when: agent_dir.stat.exists

- name: set custom profile
  set_fact:
    server_xml: "{{ custom_server_config }}"
  when: custom_server_config is defined

- name: set cloud profile
  set_fact:
    server_xml: "cloud.xml"
  when: custom_server_config is undefined and cloud is defined

- name: set clustered profile
  set_fact:
    server_xml: "clustered.xml"
  when: custom_server_config is undefined and cloud is undefined

- name: server pid
  shell: pgrep java || echo "no java process running"
  register: pid

- name: stop server
  shell: kill {{ pid.stdout }} || echo "Server was not running."

- name: Wait until server stops
  block:
    - name: Make sure server is gone
      wait_for:
        path: /proc/{{ pid.stdout }}/status
        state: absent
  rescue:
    - name: force kill
      shell: kill -9 {{ pid.stdout }} || echo "already gone!"

- name: start server
  shell: cd /opt/jdg/server/ && nohup bin/standalone.sh -c {{ server_xml }} -b $(hostname -i) &
  when: cloud is undefined

- name: start server
  shell: cd /opt/jdg/server/ && nohup bin/standalone.sh -c {{ server_xml }} -Djboss.default.jgroups.stack=s3-public -Djgroups.s3.bucket="jgroups-1" -b $(hostname -i) &
  when: cloud is defined

- name: Wait for server to start
  wait_for:
    port: 11222
    host: "{{ inventory_hostname }}"
