---
- name: Install sdkman
  shell: curl -s "https://get.sdkman.io" | bash

- name: Install JVM
  shell: |
    source ~/.bashrc
    yes y | sdk install java {{ java_version }}

- name: Create server dir
  file:
    path: /opt/jdg/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Copy server
  copy:
    src: files/servers/{{ server_zip }}
    dest: /opt/jdg/server.zip

- name: Extract Server
  unarchive:
    src: /opt/jdg/server.zip
    dest: /opt/jdg
    remote_src: true

- name: obtain server dir
  shell: ls -d /opt/jdg/*server*/ | head -1
  register: server_dir

- name: Overlay server files
  copy:
    src: ./files/servers/overlay/
    dest: "{{ server_dir.stdout }}/"
    directory_mode: yes

- name: Create agent dir
  file:
    path: /opt/agent/
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: yes

- name: Copy agent
  copy:
    src: files/agents/{{ agent_zip }}
    dest: /opt/agent/agent.zip

- name: Extract agent
  unarchive:
    src: /opt/agent/agent.zip
    dest: /opt/agent
    remote_src: true

- name: Overlay agent files
  copy:
    src: ./files/agents/overlay/
    dest: /opt/agent/
    directory_mode: yes

- name: Add Agent ops
  shell: sed -i "/^#PRESERV.*/a JAVA_OPTS=\"\$JAVA_OPTS {{ agent_opts }}\""  /opt/jdg/*/bin/standalone.conf

- name: Add GC opts
  shell: sed -i "/^#PRESERV.*/a JAVA_OPTS=\"\$JAVA_OPTS {{ gc_opts }}\""  /opt/jdg/*/bin/standalone.conf

- name: Add JFR opts
  shell: sed -i "/^#PRESERV.*/a JAVA_OPTS=\"\$JAVA_OPTS {{ fr_opts }}\""  /opt/jdg/*/bin/standalone.conf

- name: set custom profile
  set_fact:
    server_xml: "{{ custom_server_config }}"
  when: custom_server_config is defined

- name: set cloud profile
  set_fact:
    server_xml: "cloud.xml"
  when: custom_server_config is undefined and cloud is defined

- name: set clustered profile
  set_fact:
    server_xml: "clustered.xml"
  when: custom_server_config is undefined and cloud is undefined

- name: start server
  shell: cd /opt/jdg/*server*/ && nohup bin/standalone.sh -c {{ server_xml }} -b $(hostname -i) &
  when: cloud is undefined

- name: start server
  shell: cd /opt/jdg/*server*/ && nohup bin/standalone.sh -c {{ server_xml }} -Djboss.default.jgroups.stack=s3-public -Djgroups.s3.bucket="jgroups-1" -b $(hostname -i) &
  when: cloud is defined
